<<<<<<< HEAD
# Site settings
title: Amin Bashi
email: hello@aminbashi.com
description: Amin Bashi
baseurl: / 
url: aminbashi.com

twitter_username: aminbashi
github_username: amin15

# Build settings
markdown: kramdown
=======
theme: jekyll-theme-cayman
>>>>>>>
